[package]
name = "rust_p2p_file_protocol"
version = "0.1.0"
edition = "2021"


[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full"] }
libp2p = { version = "0.52", features = ["full"] }
libp2p_stream_protocol = { version = "0.1.0", path = "../libp2p_stream_protocol" }
